spring.application.name=ejercicio8

# JWT settings (moved from code to properties)
jwt.secret=MiClaveSuperSecretaYReSeguraParaElEjercicioDeProgramacionOchoAlumnoLautaroOlivero
jwt.expirationMs=3600000
